name: 'Analytics'
version: '2.0'
profile: 'customer_pipeline'
model-paths: ["models"]
seed-paths: ["seeds"]
models:
    bronze:
      +materialized: view
      +database: BRONZE
      +schema: PUBLIC
    silver:
      materialized: view
      +database: SILVER
      +schema: PUBLIC
    gold:
      materialized: table
      +database: GOLD
      +schema: PUBLIC
    
