version: 2

sources:
  - name: raw
    database: SOURCE_TEST
    schema: PUBLIC
    quoting:
      identifier: true
      database: true
      schema: true
    tables:
      - name: SOURCECUSTOMER
        description: "this table has customers which is getting from salesforce"
